on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Supply MongoDB 3.4
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 3.4
      - run: npm ci
      - run: make lint
      - name: Supply test configuration
        run: cp config/test.sample.json config/test.json
      - name: Make webservice available to be tested
        run: NODE_ENV=test node index.js &
      - run: sleep 10s
      - run: make test
